### ISSUE TITLE
Unable to execute demo

### ISSUE THREAD

**Issue by HealthSync** [YiVal/YiVal#105]
**Describe the bug**
TypeError: OpenAIPromptBasedVariationGeneratorConfig.__init__() got an unexpected keyword argument 'model_name'

**To Reproduce**
When I execute ;yival run demo/configs/animal_story.yml' I get those error

**Expected behavior**
Successful launch of demo
<img width="893" alt="Issue" src="https://github.com/YiVal/YiVal/assets/9561804/bd8d32cc-89b3-4229-8666-fd546dbc3fea">

**Version and Logs**
1.1

**Screenshots** (Optional)

**Additional context** (Optional)

**Comment by uni-zhuan** [comment]
Hello, 
Thanks for the issue! I couldn't reproduce your problem on the latest yival master branch. You can try pulling the latest branch and see if the issue persists.  Alternatively, please provide more detailed information about the version you're actually using.😃

**Comment by uni-zhuan** [comment]
Hi,
thanks for the issue. We've released an updated version of the code. Please try re-installing and then execute the command again. You may not counter this problem anymore. 😃

**Comment by HealthSync** [comment]
I'm still getting error.  I may ve doing something wrong.   Can you help me
what is going on? or please direct me a simple direction to install and
work?

(venv) MacBook-Pro YiVal-master % yival run demo/configs/animal_story.yml

Failed to run the experiment.

Error: OpenAIPromptBasedVariationGeneratorConfig.__init__() got an
unexpected keyword argument 'model_name'

Traceback (most recent call last):

  File
"/Users/xxxx/.pyenv/versions/3.10.12/lib/python3.10/site-packages/yival/cli/run.py",
line 45, in run_experiment

    runner.run(

  File
"/Users/xxx/.pyenv/versions/3.10.12/lib/python3.10/site-packages/yival/experiment/experiment_runner.py",
line 104, in run

    state.set_experiment_config(self.config)

  File
"/Users/xxx/.pyenv/versions/3.10.12/lib/python3.10/site-packages/yival/states/experiment_state.py",
line 138, in set_experiment_config

    self.initialize_variations_from_config()

  File
"/Users/xxx/.pyenv/versions/3.10.12/lib/python3.10/site-packages/yival/states/experiment_state.py",
line 106, in initialize_variations_from_config

    config_instance = config_cls(**config_data)

TypeError: OpenAIPromptBasedVariationGeneratorConfig.__init__() got an
unexpected keyword argument 'model_name'

**Comment by crazycth** [comment]
@HealthSync Hello , you can reinstall yival with pip:
```bash
pip install --upgrade poetry
```

animal_story is a multimodality demo which needs midjourney account and [the next leg](https://www.thenextleg.io/account/new)

We recommend u use our [animal_story colab](https://colab.research.google.com/drive/1DgtDZghleiLEaaNF7f4vSGJ4ChDVls2X?usp=sharing) , which we provide our the next leg key for free use ~

You can also find how to install the latest yival with poetry in this colab

**Comment by HealthSync** [comment]
Thanks,

I got this message:Access Yival from this public URL :NgrokTunnel: "
https://0811-34-122-181-236.ngrok-free.app" -> "http://localhost:8073"
Dash is running on http://127.0.0.1:8073/ * Serving Flask app '
yival.experiment.app.app' * Debug mode: off WARNING: This is a development
server. Do not use it in a production deployment. Use a production WSGI
server instead. * Running on http://127.0.0.1:8073

But when I launch http://127.0.0.1:8073/ it shows:
[image: image.png]

**Comment by uni-zhuan** [comment]
Hi,
Based on the output you mentioned, please access the former public URL https:/XXX.ngrok-free.app instead of the latter URL http://127.0.0.1:8073/ . 

We utilize ngrok to expose the local service to the public network, allowing it to be accessed via a public URL rather than using the local localhost address.

**Comment by HealthSync** [comment]
Thanks.

Now I got this error.  fyi:  I have already installed poetry

[image: image.png]

**Comment by uni-zhuan** [comment]
@HealthSync Sry, I can't see the screenshot you provided, please check and edit your last comment. 😊
